'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, MapPin } from 'lucide-react';
import { SearchBar } from '@/shared/components/ui/SearchBar';
import { FilterTabs } from '@/shared/components/ui/FilterTabs';
import { EmptyState, ErrorState, EventCardSkeleton } from '@/shared/components/ui/States';

interface Event { id:string;title:string;date:string;time:string;location:string;venue:string;category:string;passes:Array<{price:number}> }
export default function ExplorePage(){
  const [events,setEvents]=useState<Event[]>([]),[tabs,setTabs]=useState([{id:'all',label:'Everything'}]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('all');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/data/content');if(!response.ok)throw new Error();const data=await response.json();setEvents((data.events||[]).sort((a:Event,b:Event)=>+new Date(a.date)-+new Date(b.date)));setTabs([{id:'all',label:'Everything'},...data.categories.map((item:{name:string})=>({id:item.name,label:item.name}))]);}catch{setError('Explore is unavailable right now.');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const filtered=useMemo(()=>events.filter(event=>(category==='all'||event.category===category)&&`${event.title} ${event.location} ${event.venue}`.toLowerCase().includes(search.toLowerCase())),[events,category,search]);
  return <div className="px-5 sm:px-6 pt-7 pb-5 space-y-7"><header><p className="eyebrow">Find your next scene</p><h1 className="display-serif text-4xl text-[var(--ink)] mt-1">Explore</h1><p className="muted text-sm mt-2">Events, gatherings and experiences worth showing up for.</p></header><SearchBar value={search} onChange={setSearch} placeholder="Search by event, city or venue…"/><FilterTabs tabs={tabs} activeTab={category} onTabChange={setCategory}/>
    {loading?<div className="grid sm:grid-cols-2 gap-4"><EventCardSkeleton/><EventCardSkeleton/><EventCardSkeleton/></div>:error?<ErrorState message={error} onRetry={load}/>:filtered.length===0?<EmptyState title="No matching scenes" description="Try another category or a broader search." actionLabel="Reset search" actionOnClick={()=>{setSearch('');setCategory('all');}}/>:<div className="grid sm:grid-cols-2 gap-4">{filtered.map((event,index)=>{const date=new Date(event.date),min=event.passes.length?Math.min(...event.passes.map(pass=>pass.price)):0;return <Link href={`/events/${event.id}`} key={event.id} className={`editorial-card overflow-hidden group ${index===0?'sm:col-span-2 sm:grid sm:grid-cols-[1.1fr_.9fr]':''}`}><div className={`relative bg-gradient-to-br from-blue-950 via-blue-700 to-indigo-400 overflow-hidden ${index===0?'h-56 sm:h-full':'h-40'}`}><div className="absolute w-48 h-48 rounded-full border-[24px] border-white/10 -top-16 -right-8"/><span className="absolute left-4 top-4 text-white/75 eyebrow">{event.category}</span><div className="absolute bottom-4 left-4 text-white"><p className="display-serif text-4xl leading-none">{date.getDate()}</p><p className="text-[10px] uppercase tracking-[.18em]">{date.toLocaleDateString('en-IN',{month:'short',weekday:'short'})}</p></div></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">{event.time}</p><h2 className="display-serif text-2xl text-white mt-2 leading-tight">{event.title}</h2></div><span className="w-9 h-9 rounded-full brand-button grid place-items-center shrink-0"><ArrowUpRight size={16}/></span></div><p className="muted text-xs mt-4 flex gap-1.5"><MapPin size={13}/>{event.venue}, {event.location}</p><div className="mt-5 pt-4 border-t border-[var(--line)] flex justify-between text-xs"><span className="muted">Hosted experience</span><strong className="text-[var(--terra)]">From ₹{min}</strong></div></div></Link>})}</div>}
  </div>;
}
