'use client';
import { useCallback,useEffect,useState } from 'react';
import { Mail,Phone } from 'lucide-react';
import { DashboardSkeleton,ErrorState } from '@/shared/components/ui/States';
import { LoadingButton } from '@/shared/components/ui/LoadingButton';
const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value||0);

export default function AdminPaymentsPage(){
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch('/api/data/payments',{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Payment operations unavailable');}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
  const update=async(body:any,key:string)=>{setBusy(key);setError('');try{const response=await fetch('/api/data/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Update failed');}finally{setBusy('');}};
  if(loading)return <DashboardSkeleton/>;if(!data)return <ErrorState message={error||'Payments unavailable'} onRetry={load}/>;
  return <div className="space-y-7"><header><p className="eyebrow">Finance desk</p><h1 className="display-serif text-4xl mt-1">Seller payments</h1><p className="muted mt-1">UPI destinations, withdrawal requests and seller contact requests.</p></header>{error&&<p className="rounded-xl bg-red-500/10 border border-red-500/20 p-3 text-red-400 text-sm">{error}</p>}
    <section className="space-y-3"><h2 className="display-serif text-2xl">Seller accounts</h2><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{data.sellers.map((seller:any)=><article key={seller.id} className="editorial-card p-4"><p className="font-semibold">{seller.name}</p><p className="muted text-xs mt-1">{seller.email}</p><p className="display-serif text-2xl mt-4">{money(seller.revenue)}</p><p className="eyebrow mt-1">Lifetime earned</p><div className="rounded-xl bg-[var(--soft)] p-3 mt-4"><p className="text-xs font-mono">{seller.profile?.upiId||'UPI not configured'}</p><p className="muted text-[10px] mt-1">{seller.profile?.phone||'No phone number'}</p></div><div className="flex gap-2 mt-3"><a href={`mailto:${seller.email}`} className="rounded-xl border border-[var(--line)] p-2"><Mail size={15}/></a>{seller.profile?.phone&&<a href={`tel:${seller.profile.phone}`} className="rounded-xl border border-[var(--line)] p-2"><Phone size={15}/></a>}</div></article>)}</div></section>
    <section className="space-y-3"><h2 className="display-serif text-2xl">Withdrawal queue</h2>{data.withdrawals.length?data.withdrawals.map((item:any)=><Withdrawal key={item.id} item={item} busy={busy} update={update}/>):<div className="editorial-card p-8 text-center muted">No withdrawal requests.</div>}</section>
    <section className="space-y-3"><h2 className="display-serif text-2xl">Messages & callbacks</h2>{data.contacts.length?data.contacts.map((item:any)=><Contact key={item.id} item={item} busy={busy} update={update}/>):<div className="editorial-card p-8 text-center muted">No contact requests.</div>}</section>
  </div>;
}

function Withdrawal({item,busy,update}:{item:any;busy:string;update:(body:any,key:string)=>void}){const [status,setStatus]=useState(item.status),[reference,setReference]=useState(item.paymentReference||''),[note,setNote]=useState(item.adminNote||'');return <article className="editorial-card p-4 grid lg:grid-cols-[1fr_180px_220px_auto] gap-3 items-end"><div><p className="font-semibold">{item.seller?.name||'Seller'} · {money(item.amount)}</p><p className="muted text-xs mt-1">{item.seller?.email} · {new Date(item.requestedAt).toLocaleString('en-IN')}</p>{item.sellerNote&&<p className="text-xs mt-2">“{item.sellerNote}”</p>}</div><label className="text-[10px] muted">Status<select value={status} onChange={event=>setStatus(event.target.value)} className="app-input w-full rounded-xl p-2.5 mt-1"><option>REQUESTED</option><option>PROCESSING</option><option>PAID</option><option>REJECTED</option></select></label><div className="grid gap-2"><input value={reference} onChange={event=>setReference(event.target.value)} placeholder="UPI transaction reference" className="app-input rounded-xl p-2.5 text-xs"/><input value={note} onChange={event=>setNote(event.target.value)} placeholder="Note to seller" className="app-input rounded-xl p-2.5 text-xs"/></div><LoadingButton loading={busy===item.id} onClick={()=>update({action:'update-withdrawal',id:item.id,status,paymentReference:reference,adminNote:note},item.id)} className="brand-button rounded-xl px-4 py-2.5 text-xs">Save</LoadingButton></article>}
function Contact({item,busy,update}:{item:any;busy:string;update:(body:any,key:string)=>void}){const [status,setStatus]=useState(item.status),[note,setNote]=useState(item.adminNote||'');return <article className="editorial-card p-4 grid lg:grid-cols-[1fr_170px_220px_auto] gap-3 items-end"><div><p className="font-semibold">{item.seller?.name||'Seller'} · {item.type==='CALL'?'Callback':'Message'}</p><p className="muted text-xs mt-1">{item.seller?.email}{item.phone?` · ${item.phone}`:''}</p><p className="text-sm mt-3 leading-6">{item.message}</p></div><select value={status} onChange={event=>setStatus(event.target.value)} className="app-input rounded-xl p-2.5"><option>OPEN</option><option>CONTACTED</option><option>CLOSED</option></select><input value={note} onChange={event=>setNote(event.target.value)} placeholder="Internal/update note" className="app-input rounded-xl p-2.5 text-xs"/><LoadingButton loading={busy===item.id} onClick={()=>update({action:'update-contact',id:item.id,status,adminNote:note},item.id)} className="brand-button rounded-xl px-4 py-2.5 text-xs">Save</LoadingButton></article>}
