'use client';
import { useCallback, useEffect, useState } from 'react';
import { Check, Eye, EyeOff, GripVertical, LayoutGrid, Pencil, Plus, Rows3, Sparkles, Trash2 } from 'lucide-react';
import { LoadingButton } from '@/shared/components/ui/LoadingButton';
import { DashboardSkeleton } from '@/shared/components/ui/States';
import { useActionDialog } from '@/shared/components/ui/ActionDialog';
import { invalidateClientCache } from '@/shared/lib/client-data-cache';

type Category={id:string;name:string;active:boolean;sortOrder:number};
type Event={id:string;title:string;category:string;status:string;date:string};
type Layout='FEATURE'|'GRID'|'RAIL'|'COMPACT';
type Section={id:string;title:string;eyebrow:string;layout:Layout;eventIds:string[];active:boolean;sortOrder:number};
const layouts:[Layout,string,typeof Sparkles][]=[['FEATURE','Spotlight',Sparkles],['GRID','Poster grid',LayoutGrid],['RAIL','Swipe rail',Rows3],['COMPACT','Compact list',GripVertical]];
const blankSection:Omit<Section,'id'>={title:'',eyebrow:'',layout:'FEATURE',eventIds:[],active:true,sortOrder:0};

export default function ContentPage(){
  const [categories,setCategories]=useState<Category[]>([]),[events,setEvents]=useState<Event[]>([]),[sections,setSections]=useState<Section[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[error,setError]=useState('');
  const [categoryName,setCategoryName]=useState(''),[draft,setDraft]=useState<(Omit<Section,'id'>&{id?:string})>(blankSection);
  const [dragging,setDragging]=useState<number|null>(null);
  const {ask,dialog}=useActionDialog();
  const load=useCallback(async()=>{setError('');try{const response=await fetch('/api/data/content?scope=admin');if(!response.ok)throw new Error();const data=await response.json();setCategories(data.categories);setEvents(data.events);setSections(data.sections);}catch{setError('Could not load homepage controls.');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const act=async(body:Record<string,unknown>)=>{const response=await fetch('/api/data/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Update failed');invalidateClientCache('public:content');invalidateClientCache('public:event:');return data;};
  const addCategory=async()=>{if(!categoryName.trim())return;setSaving('category');setError('');try{await act({action:'create-category',name:categoryName,sortOrder:categories.length*10});setCategoryName('');await load();}catch(e){setError(e instanceof Error?e.message:'Could not add category');}finally{setSaving('');}};
  const editCategory=async(category:Category)=>{const name=await ask({title:'Rename category',description:'Every event currently using this category will be updated too.',confirmLabel:'Save name',field:{label:'Category name',defaultValue:category.name,required:true}});if(!name)return;setSaving(category.id);try{await act({action:'update-category',...category,name});await load();}catch(e){setError(e instanceof Error?e.message:'Could not update category');}finally{setSaving('');}};
  const toggleCategory=async(category:Category)=>{setSaving(category.id);try{await act({action:'update-category',...category,active:!category.active});await load();}catch(e){setError(e instanceof Error?e.message:'Could not update category');}finally{setSaving('');}};
  const removeCategory=async(category:Category)=>{const alternatives=categories.filter(item=>item.id!==category.id);if(!alternatives.length){setError('Keep at least one category.');return;}const used=events.some(event=>event.category===category.name);const replacement=await ask({title:`Delete ${category.name}?`,description:used?'Choose where its existing events should move. This cannot be undone.':'This category is unused and will be removed permanently.',confirmLabel:'Delete category',tone:'danger',field:used?{label:'Move existing events to',choices:alternatives.map(item=>({label:item.name,value:item.name})),required:true}:undefined});if(!replacement)return;setSaving(category.id);try{await act({action:'delete-category',id:category.id,replacementCategory:used?replacement:''});await load();}catch(e){setError(e instanceof Error?e.message:'Could not delete category');}finally{setSaving('');}};
  const saveSection=async()=>{if(!draft.title.trim())return;setSaving('section');setError('');try{await act({action:'save-section',...draft,sortOrder:draft.id?draft.sortOrder:(sections.length+1)*10});setDraft(blankSection);await load();}catch(e){setError(e instanceof Error?e.message:'Could not save section');}finally{setSaving('');}};
  const removeSection=async(section:Section)=>{if(!await ask({title:`Delete “${section.title}”?`,description:'It will disappear from the customer home immediately.',confirmLabel:'Delete section',tone:'danger'}))return;setSaving(section.id);try{await act({action:'delete-section',id:section.id});await load();}catch(e){setError(e instanceof Error?e.message:'Could not delete section');}finally{setSaving('');}};
  const persistOrder=async(next:Section[],previous:Section[])=>{setSections(next);setSaving('reorder');setError('');try{await act({action:'reorder-sections',ids:next.map(section=>section.id)});setSections(current=>current.map((section,position)=>({...section,sortOrder:(position+1)*10})));}catch(e){setSections(previous);setError(e instanceof Error?e.message:'Section order could not be saved');}finally{setSaving('');setDragging(null);}};
  const dropSection=async(target:number)=>{if(dragging===null||dragging===target){setDragging(null);return;}const previous=[...sections],next=[...sections],moved=next.splice(dragging,1)[0];next.splice(target,0,moved);await persistOrder(next,previous);};
  if(loading)return <DashboardSkeleton/>;
  return <div className="space-y-8"><header><p className="eyebrow">Discovery control room</p><h1 className="display-serif text-4xl text-[var(--ink)] mt-2">Home & categories</h1><p className="muted text-sm mt-2 max-w-2xl">Control the vocabulary sellers use and compose exactly what customers see on their home screen.</p></header>
    {error&&<div className="rounded-2xl border border-red-500/25 bg-red-500/10 text-red-400 p-4 text-sm">{error}</div>}
    <section className="surface rounded-[1.75rem] p-5 space-y-5"><div><p className="eyebrow">Taxonomy</p><h2 className="display-serif text-2xl text-[var(--ink)] mt-1">Event categories</h2></div><div className="flex gap-2"><input value={categoryName} onChange={e=>setCategoryName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addCategory()} placeholder="New category name" className="app-input flex-1 rounded-xl px-4 py-3 text-sm"/><LoadingButton loading={saving==='category'} onClick={addCategory} loadingLabel="Adding" className="brand-button rounded-xl px-4 font-semibold"><Plus size={16}/>Add</LoadingButton></div><div className="flex flex-wrap gap-2">{categories.map(category=><div key={category.id} className={`flex items-center gap-1 rounded-full border pl-3 pr-1 py-1 ${category.active?'border-[var(--line)] bg-[var(--soft)]':'border-dashed border-[var(--line)] opacity-55'}`}><span className="text-xs font-semibold">{category.name}</span><button onClick={()=>toggleCategory(category)} className="w-7 h-7 grid place-items-center" title={category.active?'Hide':'Show'}>{category.active?<Eye size={13}/>:<EyeOff size={13}/>}</button><button onClick={()=>editCategory(category)} className="w-7 h-7 grid place-items-center"><Pencil size={13}/></button><button onClick={()=>removeCategory(category)} className="w-7 h-7 grid place-items-center text-red-400"><Trash2 size={13}/></button></div>)}</div></section>
    <section className="grid lg:grid-cols-[.9fr_1.1fr] gap-5"><div className="surface rounded-[1.75rem] p-5 space-y-5 self-start"><div><p className="eyebrow">Section editor</p><h2 className="display-serif text-2xl text-[var(--ink)] mt-1">{draft.id?'Edit section':'Add a section'}</h2></div><div className="space-y-3"><input value={draft.eyebrow} onChange={e=>setDraft({...draft,eyebrow:e.target.value})} placeholder="Small label — e.g. Curated for you" className="app-input w-full rounded-xl px-4 py-3 text-sm"/><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Section heading" className="app-input w-full rounded-xl px-4 py-3 text-sm"/><div className="grid grid-cols-2 gap-2">{layouts.map(([id,label,Icon])=><button key={id} onClick={()=>setDraft({...draft,layout:id})} className={`rounded-xl border p-3 text-left ${draft.layout===id?'border-blue-500 bg-blue-500/10':'border-[var(--line)]'}`}><Icon size={17}/><span className="text-xs font-semibold block mt-2">{label}</span></button>)}</div><div className="grid grid-cols-2 gap-3"><label className="text-xs muted">Order<input type="number" value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})} className="app-input w-full rounded-xl px-3 py-2 mt-1"/></label><label className="flex items-end pb-2 gap-2 text-xs"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Visible</label></div><div><p className="eyebrow mb-2">Events · {draft.eventIds.length} selected</p><div className="max-h-64 overflow-y-auto space-y-1 pr-1">{events.filter(event=>event.status==='ACTIVE').map(event=><label key={event.id} className="flex items-center gap-3 rounded-xl p-3 bg-[var(--soft)] cursor-pointer"><input type="checkbox" checked={draft.eventIds.includes(event.id)} onChange={()=>setDraft({...draft,eventIds:draft.eventIds.includes(event.id)?draft.eventIds.filter(id=>id!==event.id):[...draft.eventIds,event.id]})}/><span className="min-w-0"><span className="text-xs font-semibold block truncate">{event.title}</span><span className="muted text-[10px]">{event.category}</span></span></label>)}</div></div></div><div className="flex gap-2"><LoadingButton loading={saving==='section'} onClick={saveSection} loadingLabel="Saving" className="brand-button rounded-xl px-5 py-3 font-semibold"><Check size={16}/>Save section</LoadingButton>{draft.id&&<button onClick={()=>setDraft(blankSection)} className="rounded-xl border border-[var(--line)] px-4 text-sm">Cancel</button>}</div></div>
      <div className="space-y-3"><div><p className="eyebrow">Live composition</p><h2 className="display-serif text-2xl text-[var(--ink)] mt-1">Homepage sections</h2><p className="muted text-xs mt-1">Drag a tile by its handle to change the customer-home order.</p></div>{sections.length===0&&<div className="surface rounded-2xl p-8 text-center muted text-sm">No sections yet. Create the first one.</div>}{sections.map((section,index)=><article key={section.id} data-section-index={index} onDragOver={event=>event.preventDefault()} onDrop={()=>dropSection(index)} className={`surface rounded-2xl p-4 flex items-center gap-3 transition ${dragging===index?'opacity-40 scale-[.98]':'opacity-100'}`}><button draggable disabled={saving==='reorder'} onDragStart={event=>{setDragging(index);event.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setDragging(null)} aria-label={`Drag ${section.title} to reorder`} className="w-9 h-12 rounded-xl bg-[var(--soft)] grid place-items-center cursor-grab active:cursor-grabbing touch-none"><GripVertical size={18}/></button><span className="display-serif text-2xl muted w-7">{String(index+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><div className="flex gap-2 items-center"><h3 className="font-semibold truncate">{section.title}</h3>{!section.active&&<EyeOff size={13} className="muted"/>}</div><p className="muted text-xs mt-1">{section.layout.toLowerCase()} · {section.eventIds.length} events</p></div><button onClick={()=>setDraft(section)} className="w-9 h-9 grid place-items-center rounded-xl bg-[var(--soft)]"><Pencil size={15}/></button><button onClick={()=>removeSection(section)} className="w-9 h-9 grid place-items-center rounded-xl bg-red-500/10 text-red-400"><Trash2 size={15}/></button></article>)}</div></section>
    {dialog}
  </div>;
}
