'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { CalendarDays, ChevronRight, Download, Monitor, Moon, QrCode, Sun, Ticket, UserRound } from 'lucide-react';
import { authService, type AuthUser } from '@/features/auth';
import { usePWAInstall } from '@/shared/lib/use-pwa';
import { useTheme, type ThemePreference } from '@/shared/components/theme/ThemeProvider';
import { LoadingButton } from '@/shared/components/ui/LoadingButton';
import { Skeleton } from '@/shared/components/ui/States';

export default function ProfilePage(){
  const router=useRouter(),[user,setUser]=useState<AuthUser|null>(null),[loggingOut,setLoggingOut]=useState(false);
  const [stats,setStats]=useState({passes:0,active:0,bookings:0});
  const {theme,setTheme}=useTheme(),{canInstall,isInstalled,install}=usePWAInstall();
  useEffect(()=>{authService.getCurrentUser().then(async account=>{setUser(account);if(!account)return;const [passesResponse,ordersResponse]=await Promise.all([fetch(`/api/data/passes?userId=${account.id}`),fetch(`/api/data/orders?userId=${account.id}`)]);const passes=passesResponse.ok?await passesResponse.json():[],orders=ordersResponse.ok?await ordersResponse.json():[];setStats({passes:passes.length,active:passes.filter((pass:{status:string})=>pass.status==='ACTIVE').length,bookings:orders.length});});},[]);
  const logout=async()=>{setLoggingOut(true);await authService.logout();router.replace('/');router.refresh();};
  const links=user?.role==='SELLER'?[['/seller/events','Manage events',CalendarDays],['/scanner','Entry scanner',QrCode]] as const:user?.role==='ADMIN'?[['/admin','Admin office',UserRound],['/scanner','Entry scanner',QrCode]] as const:[['/passes','My passes',Ticket]] as const;
  return <div className="px-5 sm:px-6 pt-7 pb-8 space-y-8"><header><p className="eyebrow">Account</p><h1 className="display-serif text-white text-4xl mt-1">Your profile</h1></header>
    <section className="editorial-card p-6 text-center">{user?<><div className="w-20 h-20 rounded-full brand-button grid place-items-center display-serif text-3xl uppercase mx-auto ring-4 ring-[var(--surface)]">{user.name[0]}</div><p className="display-serif text-3xl text-white mt-4">{user.name}</p><p className="muted text-xs mt-1">{user.email}</p><div className="grid grid-cols-3 divide-x divide-[var(--line)] mt-6"><div><p className="display-serif text-2xl text-white">{stats.passes}</p><p className="eyebrow mt-1">Passes</p></div><div><p className="display-serif text-2xl text-white">{stats.active}</p><p className="eyebrow mt-1">Active</p></div><div><p className="display-serif text-2xl text-white">{stats.bookings}</p><p className="eyebrow mt-1">Bookings</p></div></div></>:<><Skeleton className="w-20 h-20 rounded-full mx-auto"/><Skeleton className="h-7 w-1/2 mx-auto mt-4"/><Skeleton className="h-3 w-2/3 mx-auto mt-2"/></>}</section>
    {user?.role==='USER'&&<section className="rounded-2xl bg-[#172554] text-white p-5 flex items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-blue-300">Your wallet</p><p className="display-serif text-xl mt-2">{stats.active} active pass{stats.active===1?'':'es'}</p><p className="text-white/55 text-xs mt-1">Ready whenever you are.</p></div><Link href="/explore" className="rounded-full bg-[#3158d4] px-4 py-2.5 text-xs font-semibold">Explore</Link></section>}
    <section className="space-y-3"><div><p className="eyebrow">Appearance</p><h2 className="display-serif text-xl text-white mt-1">Make it yours</h2></div><div className="editorial-card p-1.5 grid grid-cols-3 gap-1">{([['light','Light',Sun],['dark','Dark',Moon],['system','Auto',Monitor]] as [ThemePreference,string,typeof Sun][]).map(([value,label,Icon])=><button key={value} onClick={()=>setTheme(value)} className={`flex items-center justify-center gap-2 rounded-xl py-3 text-xs font-semibold transition ${theme===value?'brand-button':'muted hover:bg-[var(--soft)]'}`}><Icon size={16}/>{label}</button>)}</div></section>
    <section className="space-y-3"><p className="eyebrow">Shortcuts</p><div className="editorial-card overflow-hidden divide-y divide-[var(--line)]">{links?.map(([href,label,Icon])=><Link href={href} key={href} className="flex items-center gap-3 p-4 hover:bg-[var(--soft)] transition"><span className="w-10 h-10 rounded-xl bg-[var(--soft)] text-[var(--terra)] grid place-items-center"><Icon size={18}/></span><span className="flex-1 text-sm font-semibold text-white">{label}</span><ChevronRight size={16} className="muted"/></Link>)}</div></section>
    {!isInstalled&&<section className="editorial-card p-5 flex items-center gap-4"><span className="w-11 h-11 rounded-xl brand-button grid place-items-center"><Download size={18}/></span><div className="flex-1"><p className="text-sm font-semibold text-white">Install Scenezy</p><p className="muted text-xs mt-1">Faster access from your home screen.</p></div><button onClick={()=>canInstall?install():undefined} disabled={!canInstall} className="rounded-full border border-[var(--line)] px-4 py-2 text-xs font-semibold disabled:opacity-45">Install</button></section>}
    <LoadingButton loading={loggingOut} loadingLabel="Signing out…" onClick={logout} className="w-full rounded-full border border-red-500/25 text-red-400 py-3.5 text-sm font-semibold">Sign out</LoadingButton><p className="text-center muted text-[10px]">Scenezy · Version 0.4</p>
  </div>;
}
