'use client';
import { useCallback,useEffect,useState } from 'react';
import { Banknote,CheckCircle2,Clock3,Headphones,IndianRupee,MessageSquare,Phone,WalletCards } from 'lucide-react';
import { ErrorState,PageLoading } from '@/shared/components/ui/States';
import { LoadingButton } from '@/shared/components/ui/LoadingButton';

const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value||0);
const badge:Record<string,string>={PAID:'text-green-400 bg-green-500/10',PROCESSING:'text-blue-400 bg-blue-500/10',REQUESTED:'text-amber-400 bg-amber-500/10',REJECTED:'text-red-400 bg-red-500/10'};

export default function SellerPaymentsPage(){
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const [profile,setProfile]=useState({upiId:'',phone:''}),[withdrawal,setWithdrawal]=useState({amount:'',note:''}),[contact,setContact]=useState({type:'MESSAGE',message:'',phone:''});
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch('/api/data/payments',{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);setProfile({upiId:body.profile?.upiId||'',phone:body.profile?.phone||''});setContact(value=>({...value,phone:body.profile?.phone||value.phone}));setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Payments could not be loaded');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const post=async(body:any,key:string)=>{setBusy(key);setError('');try{const response=await fetch('/api/data/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);await load();return true;}catch(caught){setError(caught instanceof Error?caught.message:'Request failed');return false;}finally{setBusy('');}};
  if(loading)return <PageLoading message="Opening payments..."/>;if(!data)return <ErrorState message={error||'Payments unavailable'} onRetry={load}/>;
  const summary=data.summary;
  return <div className="px-4 pt-7 pb-8 space-y-7"><header><p className="eyebrow">Seller finance</p><h1 className="display-serif text-4xl mt-1">Payments</h1><p className="muted text-xs mt-2">Track earnings, request a payout, or speak with Scenezy.</p></header>
    <section className="grid grid-cols-2 gap-3">{[[WalletCards,'Earned',summary.revenue],[Banknote,'Available',summary.available],[Clock3,'In progress',summary.pending],[CheckCircle2,'Paid',summary.paid]].map(([Icon,label,value]:any)=><article key={label} className="editorial-card p-4"><Icon size={18} className="text-blue-500"/><p className="display-serif text-2xl mt-4">{money(value)}</p><p className="muted text-[10px] uppercase tracking-wider mt-1">{label}</p></article>)}</section>
    <section className="editorial-card p-5 space-y-4"><div><p className="eyebrow">Payout destination</p><h2 className="display-serif text-2xl mt-1">Your UPI</h2></div><label className="block text-xs muted">UPI ID<input value={profile.upiId} onChange={event=>setProfile({...profile,upiId:event.target.value})} placeholder="name@bank" className="app-input w-full rounded-xl px-4 py-3 mt-2"/></label><label className="block text-xs muted">Phone number<input value={profile.phone} onChange={event=>setProfile({...profile,phone:event.target.value})} placeholder="+91 98765 43210" className="app-input w-full rounded-xl px-4 py-3 mt-2"/></label><LoadingButton loading={busy==='profile'} loadingLabel="Saving..." onClick={()=>post({action:'save-profile',...profile},'profile')} className="brand-button w-full rounded-xl py-3 text-sm font-semibold">Save payment details</LoadingButton></section>
    <section className="editorial-card p-5 space-y-4"><div><p className="eyebrow">Available {money(summary.available)}</p><h2 className="display-serif text-2xl mt-1">Request payment</h2></div><div className="relative"><IndianRupee size={17} className="absolute left-4 top-3.5 muted"/><input type="number" min="1" max={summary.available} value={withdrawal.amount} onChange={event=>setWithdrawal({...withdrawal,amount:event.target.value})} placeholder="Amount" className="app-input w-full rounded-xl py-3 pl-10 pr-4"/></div><textarea value={withdrawal.note} onChange={event=>setWithdrawal({...withdrawal,note:event.target.value})} placeholder="Optional note" rows={2} className="app-input w-full rounded-xl p-4 resize-none"/><LoadingButton disabled={!data.profile||summary.available<1} loading={busy==='withdraw'} loadingLabel="Requesting..." onClick={async()=>{if(await post({action:'request-withdrawal',amount:Number(withdrawal.amount),note:withdrawal.note},'withdraw'))setWithdrawal({amount:'',note:''});}} className="brand-button w-full rounded-xl py-3 text-sm font-semibold">Request withdrawal</LoadingButton>{!data.profile&&<p className="text-amber-400 text-xs">Save your UPI ID first.</p>}</section>
    {error&&<p className="rounded-xl bg-red-500/10 border border-red-500/20 p-3 text-red-400 text-xs">{error}</p>}
    <section className="space-y-3"><div><p className="eyebrow">History</p><h2 className="display-serif text-2xl mt-1">Past payouts</h2></div>{data.withdrawals.length?data.withdrawals.map((item:any)=><article key={item.id} className="editorial-card p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{money(item.amount)}</p><p className="muted text-[10px] mt-1">{new Date(item.requestedAt).toLocaleDateString('en-IN')}</p></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold h-fit ${badge[item.status]||'muted'}`}>{item.status}</span></div>{item.paymentReference&&<p className="muted font-mono text-[10px] mt-3">Ref: {item.paymentReference}</p>}{item.adminNote&&<p className="muted text-xs mt-2">{item.adminNote}</p>}</article>):<div className="editorial-card p-7 text-center muted text-sm">No payout requests yet.</div>}</section>
    <section className="editorial-card p-5 space-y-4"><div className="flex gap-3"><Headphones className="text-blue-500"/><div><h2 className="font-semibold">Need help?</h2><p className="muted text-xs mt-1">Send a message or request a callback.</p></div></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>setContact({...contact,type:'MESSAGE'})} className={`rounded-xl p-3 text-xs font-semibold border ${contact.type==='MESSAGE'?'border-blue-500 bg-blue-500/10 text-blue-400':'border-[var(--line)]'}`}><MessageSquare size={16} className="inline mr-2"/>Message</button><button onClick={()=>setContact({...contact,type:'CALL'})} className={`rounded-xl p-3 text-xs font-semibold border ${contact.type==='CALL'?'border-blue-500 bg-blue-500/10 text-blue-400':'border-[var(--line)]'}`}><Phone size={16} className="inline mr-2"/>Request call</button></div>{contact.type==='CALL'&&<input value={contact.phone} onChange={event=>setContact({...contact,phone:event.target.value})} placeholder="Callback number" className="app-input w-full rounded-xl px-4 py-3"/>}<textarea value={contact.message} onChange={event=>setContact({...contact,message:event.target.value})} placeholder="How can we help?" rows={3} className="app-input w-full rounded-xl p-4 resize-none"/><LoadingButton loading={busy==='contact'} loadingLabel="Sending..." onClick={async()=>{if(await post({action:'contact',...contact},'contact'))setContact(value=>({...value,message:''}));}} className="brand-button w-full rounded-xl py-3 text-sm font-semibold">{contact.type==='CALL'?'Request callback':'Send message'}</LoadingButton></section>
  </div>;
}
